version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend:/app
    depends_on:
      - database
    command: npm start

  database:
    image: postgres:latest
    container_name: voulezvous_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: voulezvous
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voulezvous
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: